### ISSUE TITLE
Add discrete distribution subtraction

### ISSUE THREAD

**Issue by RaphaelS1** [xoopR/distr6#135]
Currently subtraction of distributions (convolution add=F) is supported for continuous distributions only as I kept running into problems with the discrete case. Implement for v1.1.

**Comment by fkiraly** [comment]
how is this not a sub-case of addition? Or is it?

**Comment by RaphaelS1** [comment]
For some strange reason, addition works for discrete and continuous. Then the subcase of subtraction works for continuous, but, and I have no idea why not, it doesn't for discrete
