### ISSUE TITLE
pmf vs pdf & accessing components of mixed distributions

### ISSUE THREAD

**Issue by fkiraly** [xoopR/distr6#147]
I was brought onto this by discussion on #143:

mixed distributions on the real (without singular part which is irrelevant in practical stats) can always be decomposed into a pure (discrete) part and an (absolutely w.r.t. Lebesgue) continuous part.

Thus, they can always be uniquely written as a mixture by specifying the pure part, continuous part, and one of the mixture weights - unique, unless the distribution wasn't mixed to start with.

Now from an API perspective, not every mixed distribution might have been constructed via the mixture compositor, even though it's always possible to construct something representing the same mathematical object through the compositor.

Question here: should we have dedicated API points for accessing pure and continuous parts? Given that we're currently using `pdf` for accessing what is, in fact, a p.m.f. (probability mass function), a slightly refined interface could return the continuous part via `pdf` and the discrete part via `pmf`, if these exist, and have some point for the mixture weights.

I admit these distributions are more exotic, but the use case I'm thinking of is Huberization: this results in a mixed distribution in general, which was *not* obtained by the mixture compositor, but by the Huberization wrapper.

**Comment by fkiraly** [comment]
Just to clarify terminology: one would use `pdf`, as in probability density function, only for the density of an absolutely continuous distribution (more formally, for the Radon-Nikodym derivative w.r.t. the Lebesgue measure of a distribution that possesses one).

**Comment by RaphaelS1** [comment]
> Question here: should we have dedicated API points for reading pure and continuous parts? Given that we're currently using pdf for accessing what is, in fact, a p.m.f. (probability mass function), a slightly refined interface could return the continuous part via pdf and the discrete part via pmf, if these exist, and have some point for the mixture weights.

I think this would be too confusing. I believe `distr` does this well with functions for decomposing mixtures as discussed in #130

**Comment by fkiraly** [comment]
But `decomposeMixtures` as in #130 works only for mixed distributions which were obtained from constructing them via the mixture compositor!

Distributions can be mixed (as a property), without them coming out of the mixture compositor, e.g., out of the Huberization wrapper.

**Comment by RaphaelS1** [comment]
Yes but I believe the functionality in `distr` separates these two cases and works for both

**Comment by fkiraly** [comment]
Perhaps, but if you have a "decompositor" that works with every distribution, and what it does is to access a key mathematical property (is it mixed? pure/mixed parts), one can ask: should that not actually have been a method of the core interface, in the first place?

**Comment by RaphaelS1** [comment]
Isn't that the same as the `valueSupport` trait that returns one of `discrete/continuous/mixture`?

**Comment by fkiraly** [comment]
but it doesn't give you the two different component in case it's mixed.

**Comment by fkiraly** [comment]
so maybe just to disambiguate, since it's a common confusion in literature.
Let's consider distributions over the reals only, and we distinguish two pieces of terminology:

(a) a distribution is called *mixed* if it has a non-trivial pure and a non-trivial continuous part. I.e., the canonical mixture coefficients for pure/continuous are both non-zero.
(b) a distribution is called a *mixture* if it has been constructed/declared as a non-trivial mixture of other distributions.

(a) is a "proper" mathematical definition, and hence being mixed is a *mathematical property* of a distribution. (b) is an algorithmic definition, and only makes sense in a context where you can explicitly construct mixtures. It can be made precise in the context of first-order calculus (of distribution construction), but it's *not* a mathematical property of a distribution since it makes reference to how you obtained the distribution.

The two concepts are related, (a) being mathematical and (b) being algorithmical: a mixed distribution can always be algorithmically constructed as a mixture of a discrete and a continuous one, but it need not have been obtained in that way. On the other hand, a non-trivial mixture of discrete and continuous distributions is always mixed, but not all mixtures are mixed - e.g., mixtures of Gaussians are continuous distributions, not mixed ones in the sense of (a).

My question in this thread is whether we should have dedicated interfaces to represent the components (pmf and pdf) of a *mixed* distribution, which needs not be a *mixture*, e.g., as per the (algorithmic) mixture distribution constructor.

**Comment by fkiraly** [comment]
in an attempt to re-start this thread: what about adopting the following convention?

*absolutely continuous distributions over the reals* have `pdf` but no `pmf` method. `cdf` is integral of `pdf`.

*discrete distributions over the reals* have `pmf` but no `pdf` method. `cdf` is summation over `pmf`.

*Discrete distributions over arbitrary domains* have `pmf` method but neither `pdf` nor `cdf`.

*Mixed distributions over the reals* have `pdf`, `pmf` and `cdf`. Here, `cdf` is integral over `pdf` plus summation over `pmf`. The convention is that the full integral of `pdf` is the mass of the continuous part, whereas the complete sum over `pmf` is the mass of the pure part.

**Comment by fkiraly** [comment]
... any comments (or decisions)?

**Comment by RaphaelS1** [comment]
I think that whilst not mathematically correct, distributions.jl made the correct decision in simplifying pdfs and pmfs to a single `density` function. If we change this now and add `pmf` this is a major change that will significantly break any existing code dependent on `distr6`, of course at some point a v2 will be required and I think we can add those methods then, but I don't think we should be doing this just yet.

In regards to the specific point about mixtures, we can easily decompose mixtures created by the wrapper `MixtureDistribution` by accessing internal models via `wrappedModels` but we cannot do this easily for user-supplied mixture distributions; this is another example of where we need to improve our numerical results. But, I do think this is a low priority task

**Comment by fkiraly** [comment]
>distributions.jl made the correct decision in simplifying pdfs and pmfs to a single density function

I'm really not sure about this...
If you only have a single method, how do you distinguish whether the return value is *mass* or *mass density*?

**Comment by RaphaelS1** [comment]
99% of users won't think about this and it should be intuitive by context

**Comment by fkiraly** [comment]
disagreed - there's a difference between being wrong and being counterintuitive...

**Comment by fkiraly** [comment]
but maybe you can explain what you have in mind.
Let's look at a common example: a distribution over the positive reals with 0.5 mass on "0", and exponential otherwise.

What is, in this case, intuitive behaviour when calling `pdf`?
