### ISSUE TITLE
Improve CoreStatistics Results

### ISSUE THREAD

**Issue by RaphaelS1** [xoopR/distr6#159]
* log-pdf
* log-cdf
* `mean` calculated from `cdf` if available

**Comment by fkiraly** [comment]
how would you compute `mean` from `cdf` without integration?

You probably mean `median`, which can be obtained by a simple inversion?

**Comment by RaphaelS1** [comment]
No we would still use integration but as you pointed out, this can be more efficient than using the `pdf` when the `cdf` is available

**Comment by fkiraly** [comment]
I don't remember pointing this out, but I guess it's true.

A different function to look for is perhaps sort-of obvious: mgf, or cgf.
