### ISSUE TITLE
Implement WeightedContinuous/Histogram

### ISSUE THREAD

**Issue by RaphaelS1** [xoopR/distr6#185]
Similar to the `WeightedDiscrete` distribution, a continuous analogue would be useful for histogram-type distributions that are defined for continuous bins.

See https://github.com/mlr-org/mlr3proba/blob/density/R/histogram.R for example

**Comment by fkiraly** [comment]
hm, can we not get this easily by a mixture of uniforms?

**Comment by RaphaelS1** [comment]
Sure but then the user needs to know how to do that, which is not necessarily obvious. We have now seen three big use-cases that justify this new distribution:

1. histogram in mlr3proba
2. some kernels in mlr3proba
3. Nick's implementations and forecasting

I envision a constructor similar to `WeightedDiscrete` which takes a `data.frame` input with columns `x, pdf, cdf` where `x` and one of `pdf` or `cdf` are compulsory. But here columns would only be `x, pdf` where `x` would be assumed to be the lower interval, i.e. `[x, x+1)`, and `pdf` is the pdf covering that interval. Then `$pdf` is calculated with `findInterval` and `cdf` same as discussed for histogram

**Comment by fkiraly** [comment]
my recommendation is to use the same implementation as for `Empirical` internally, and just make a minor change to the formulae. I believe the major change needed is to make the `pdf` piecewise constant and the `cdf` piecewise linear. The breakpoints of the histogram can be stored just as you currently store the masses of the empirical.

**Comment by RaphaelS1** [comment]
I don't understand how that works. `Empirical` takes a sample of discrete points and calculates pdf and cdf from multiplicity. Whereas this would require a set of points that have associated densities, i.e. this is used alongside functions that returns breaks and densities (e.g. `hist`) where we don't have access to the original points only the bins

**Comment by fkiraly** [comment]
Am empirical distribution is fully characterized by *masses* and *locations*.

A histogram distribution is fully characterized by *bin masses* and *bin boundaries* (aka break points).

That is, what I´m suggesting, represent the bin masses and boundaries internally, for the histogram distribution, as you currently represent masses and locations in the empirical one.

**Comment by fkiraly** [comment]
it's actually almost identical to what you said above:
>I envision a constructor similar to WeightedDiscrete which takes a data.frame input with columns x, pdf, cdf where x and one of pdf or cdf are compulsory. But here columns would only be x, pdf where x would be assumed to be the lower interval, i.e. [x, x+1), and pdf is the pdf covering that interval. Then $pdf is calculated with findInterval and cdf same as discussed for histogram

x = breakpoints
and you probably mean [x[i],x[i+1])

**Comment by fkiraly** [comment]
a minor decision to make is whether you give the constructor, or store internally, as:

breakpoints, masses
breakpoints, pdf value
breakpoints, cumulative cdf

or, for storing or construction, multiple of the above (e.g., internal data frame could have breakpoint, mass between breakpoints, pdf between breakpoints, cumulative cdf at breakpoint)

**Comment by RaphaelS1** [comment]
> and you probably mean [x[i],x[i+1])

Yes

So I think we are actually in agreement with implementation then. To be consistent with `WeightedDiscrete` it would make sense to have breakpoint, pdf value, and cumulative cdf.

**Comment by fkiraly** [comment]
ah, sorry, I now notice the confusion caused above. Wherever I said `Empirical`, I meant `WeightedDiscrete`

**Comment by RaphaelS1** [comment]
Okay makes much more sense then, we are definitely in agreement!

**Comment by fkiraly** [comment]
I wonder whether we also want breakpoint mass - this eats 33% more memory, and is only one `diff` away from cumulative cdf.

**Comment by RaphaelS1** [comment]
What's the formula difference from pdf?

**Comment by RaphaelS1** [comment]
Don't functions such as `hist` return the mass but call it density?

**Comment by fkiraly** [comment]
`mass_values = diff(ccdf_values)`
`pdf_values = mass_values/diff(breakpoints)`

**Comment by fkiraly** [comment]
you want pdf quickly since it appears in the log-loss
for the squared loss, you want the two norm of pdf, which is `sum(pdf_values * mass_values)`, or equivalently `sum(pdf_values^2 * diff(breakpoints))`

**Comment by fkiraly** [comment]
... doesn´t seem to make much of a difference?

**Comment by fkiraly** [comment]
> Don't functions such as hist return the mass but call it density?

`hist` doesn´t return mass-per-bin, or cumulative-cdf-at-breakpoint

It returns a count, which is not a parameter of a histogram distribution but an artefact of how it was estimated.

**Comment by RaphaelS1** [comment]
Okay so to confirm if a user provides bins and density:

`mass_values = pdf_values*diff(breakpoints)`
`ccdf_values = cumsum(mass_values)`

bins and mass:

`pdf_values = mass_values/diff(breakpoints)`
`ccdf_values = cumsum(mass_values)`

bins and ccdf:

`mass_values = diff(ccdf_values)`
`pdf_values = mass_values/diff(breakpoints)`

**Comment by RaphaelS1** [comment]
> The pdf field returned is a vector of values that the pdf takes within the bin.

which is surely what you call `density` ? and mass would be relatively frequency, i.e. counts/total

**Comment by fkiraly** [comment]
>Okay so to confirm if a user provides bins and density:

Yes, but I wouldn´t be sure whether we really want all those parameterisations.

>which is surely what you call density 

Yes, for the `hist` return object I meant `density` list element wherever I was referring to the `pdf` list element, sorry.

**Comment by RaphaelS1** [comment]
> Yes, but I wouldn´t be sure whether we really want all those parameterisations.

I don't see any reason why not, it's just a couple of conditionals and we can then allow the user to provide whichever form they have for maximum flexibility.

**Comment by RaphaelS1** [comment]
Given these four columns, `breaks, mass, pdf, cdf`, and input `x` we then have

```R
ind <- findInterval(val, Intervals, left.open = F, rightmost.closed = T)
pdf(x) = pdf[ind]
cdf(x) = cdf[ind-1] + (val - breaks[ind])*pdf[ind]
```

**Comment by fkiraly** [comment]
>I don't see any reason why not, it's just a couple of conditionals and we can then allow the user to provide whichever form they have for maximum flexibility.

In the constructor it might be "easy" to cover, but the same question arises for the internal representation.
