### ISSUE TITLE
Add `AbstractMixture` wrapper

### ISSUE THREAD

**Issue by RaphaelS1** [xoopR/distr6#234]
This follows from this pull request: https://github.com/mlr-org/mlr3proba/pull/161 (@aintoha @fkiraly)

Use-case: When creating a custom `Distribution` there may be times where this distribution is composed from several other distributions (or kernels). The `MixtureDistribution` doesn't allow variable weights or weights based on some function.

Proposed use: A distribution wrapped in this wrapper essentially gains a single field `wrappedModels` which is a common field added to all wrappers, in doing so it also has its `ParameterSet` extended with any distributions in `wrappedModels`. On construction a user can pass as many distributions as they like which are just stored in `wrappedModels`. This has two primary advantages:

1. Methods can be defined referencing these wrapped models which means parameters can be updated dynamically and these internal distributions aren't hard-coded without user-access
2. Users can separately access these wrapped distributions (which would be v. useful for PR above)

**Comment by fkiraly** [comment]
Yes, good idea - I felt this already existed, but apparently not?

Also, one suggestion: for efficiency purposes, it would perhaps be good to directly use `VectorDistribution` for the list of `wrappedModels`.

**Comment by RaphaelS1** [comment]
> Yes, good idea - I felt this already existed, but apparently not?

The infrastructure is there (essentially it's just a case of making a concrete version of the `Wrapper` clas)

> Also, one suggestion: for efficiency purposes, it would perhaps be good to directly use VectorDistribution for the list of wrappedModels.

Agreed but not whilst major bottlenecks remain (https://github.com/alan-turing-institute/distr6/issues/219)
