### ISSUE TITLE
Version requirement for set6 correct?

### ISSUE THREAD

**Issue by cbrueffer** [xoopR/distr6#291]
Hi,

I'm one of the maintainers for the conda-forge r-distr6` package`, currently looking at the update to version 1.8.0.

According to the `DESCRIPTION` it requires `set6 >=0.2.6`, however no such tag exists in https://github.com/xoopR/set6. Is this version requirement correct?

**Comment by RaphaelS1** [comment]
Sorry I'd updated the description but forgot to tag ! https://github.com/xoopR/set6/releases/tag/v0.2.6
