### ISSUE TITLE
`survival` property disappears after combining `VectorDistribution`s

### ISSUE THREAD

**Issue by bblodfon** [xoopR/distr6#294]
``` r
library(distr6)
#> 
#> Attaching package: 'distr6'
#> The following object is masked from 'package:stats':
#> 
#>     qqplot
#> The following object is masked from 'package:base':
#> 
#>     truncate

a = VectorDistribution$new(
  list(
    Binomial$new(prob = 0.1, size = 2),
    Binomial$new(prob = 0.6, size = 4)
  ), decorators = "ExoticStatistics"
)
a$survival(c(0,1))
#>    Binom1 Binom2
#> 1:   0.19 0.9744
#> 2:   0.01 0.8208
b = VectorDistribution$new(
  list(
    Exponential$new(rate = 2),
    Exponential$new(rate = 3)
  ), decorators = "ExoticStatistics"
)
b$survival(c(0,1))
#>         Exp1       Exp2
#> 1: 1.0000000 1.00000000
#> 2: 0.1353353 0.04978707
cmb = c(a,b)
cmb
#> Binom1 Binom2 Exp1 Exp2
cmb$pdf(c(0,1))
#>    Binom1 Binom2      Exp1      Exp2
#> 1:   0.81 0.0256 2.0000000 3.0000000
#> 2:   0.18 0.1536 0.2706706 0.1493612
cmb$survival(c(0,1))
#> Error in eval(expr, envir, enclos): attempt to apply non-function
```

<sup>Created on 2023-10-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by RaphaelS1** [comment]
ah I see now, this isn't a bug. If you ran `c(a, b, dectorators = "ExoticStatistics")` it would work. the design is that users have to manually add decorators, otherwise it could clash between the individual distributions (if say one had decorators and the other didn't), we could change this to just pull through all active decorators if better?

**Comment by bblodfon** [comment]
> we could change this to just pull through all active decorators if better?

I think that would be the best thing to do. That will solve automatically ths issue with the code that combines vector distributions in [mlr3proba](https://github.com/mlr-org/mlr3proba/blob/main/R/PredictionDataSurv.R#L93) currently.

**Comment by RaphaelS1** [comment]
Yes but you're thinking about an automated case in mlr3proba, whereas in distr6 most use-cases are more manual. So I'd actually suggest changing that line to simply `do.call(c, c(distr_list, decorators = c("CoreStatistics", "ExoticStatistics"))` which would also work

**Comment by bblodfon** [comment]
ah makes sense, I will test it and send a PR

**Comment by bblodfon** [comment]
@RaphaelS1, see example below: the main take is that the `do.call(...)` with specified decorators works for `VectorDistribution`s but not for a list of `Matdist`s or `Arrdist`s (which could happened in the `mlr3proba` code). What fails is that in this [line](https://github.com/xoopR/distr6/blob/main/R/SDistribution_Matdist.R#L349) there is no parameter to take in the decorators (they are pulled from each `Matdist` to be combined in the code) as is in the case of vector distributions [here](https://github.com/xoopR/distr6/blob/main/R/c.Distribution.R#L24). 

So I guess we either update the `distr6` code for `c.Matdist` and `c.Arrdist` to take in decorators argument and supersede the ones from the distributions passed on, or in the mlr3proba [code](https://github.com/mlr-org/mlr3proba/blob/main/R/PredictionDataSurv.R#L93) we check what type of distributions will be combined and use `do.call(c,distr_list)` for `Matdist` and `Arrdist` and the larger command with the decorators for vector distributions. Which you think is better?

``` r
library(distr6)

a = VectorDistribution$new(
  list(
    Binomial$new(prob = 0.1, size = 2),
    Binomial$new(prob = 0.6, size = 4)
  ), decorators = "ExoticStatistics"
)
a$survival(c(0,1))
#>    Binom1 Binom2
#> 1:   0.19 0.9744
#> 2:   0.01 0.8208

b = VectorDistribution$new(
  list(
    Exponential$new(rate = 2),
    Exponential$new(rate = 3)
  ), decorators = "ExoticStatistics"
)
b$survival(c(0,1))
#>         Exp1       Exp2
#> 1: 1.0000000 1.00000000
#> 2: 0.1353353 0.04978707

distr_list = list(a,b)

# do.call(fun, c(args, list(otherargs)))
res = do.call(c, c(distr_list, list(decorators = c("CoreStatistics", "ExoticStatistics"))))
# WORKS
res$survival(c(0,1))
#>    Binom1 Binom2      Exp1       Exp2
#> 1:   0.19 0.9744 1.0000000 1.00000000
#> 2:   0.01 0.8208 0.1353353 0.04978707

# use Matdist
mats = replicate(3, {
  pdf = runif(200)
  mat = matrix(pdf, 20, 10, FALSE, list(NULL, sort(sample(1:20, 10))))
  mat = t(apply(mat, 1, function(x) x / sum(x)))
  as.Distribution(mat, fun = "pdf", decorators = c("CoreStatistics", "ExoticStatistics"))
})
mats[[1]]$survival(4)
#>        [,1]      [,2]      [,3]      [,4]      [,5]      [,6]      [,7]
#> 4 0.7410428 0.8609846 0.8885526 0.7909076 0.8706527 0.8378328 0.7217763
#>        [,8]      [,9]     [,10]     [,11]     [,12]     [,13]     [,14]
#> 4 0.7964603 0.8166754 0.8655979 0.7523238 0.7273942 0.7464173 0.7576036
#>       [,15]    [,16]     [,17]     [,18]    [,19]    [,20]
#> 4 0.8171506 0.808599 0.7230959 0.7883033 0.865208 0.861679

res = do.call(c, mats)
res$survival(4)
#>        [,1]      [,2]      [,3]      [,4]      [,5]      [,6]      [,7]
#> 4 0.7410428 0.8609846 0.8885526 0.7909076 0.8706527 0.8378328 0.7217763
#>        [,8]      [,9]     [,10]     [,11]     [,12]     [,13]     [,14]
#> 4 0.7964603 0.8166754 0.8655979 0.7523238 0.7273942 0.7464173 0.7576036
#>       [,15]    [,16]     [,17]     [,18]    [,19]    [,20]     [,21]     [,22]
#> 4 0.8171506 0.808599 0.7230959 0.7883033 0.865208 0.861679 0.7498539 0.7059542
#>       [,23]     [,24]     [,25]     [,26]     [,27]     [,28]     [,29]
#> 4 0.8481509 0.7506409 0.8176953 0.9265486 0.6868151 0.7905313 0.7677403
#>       [,30]     [,31]     [,32]     [,33]     [,34]     [,35]    [,36]
#> 4 0.8816654 0.7978953 0.8439373 0.7804311 0.8030019 0.8739061 0.837768
#>       [,37]     [,38]     [,39]     [,40]     [,41]     [,42]     [,43]
#> 4 0.8183471 0.8189446 0.8692086 0.7163574 0.7486409 0.7247459 0.7722572
#>       [,44]     [,45]     [,46]     [,47]     [,48]     [,49]     [,50]
#> 4 0.4690807 0.8581354 0.7102764 0.7593674 0.6861375 0.8253788 0.4603394
#>       [,51]     [,52]     [,53]     [,54]     [,55]     [,56]     [,57]
#> 4 0.8545256 0.7756999 0.7581016 0.5813778 0.6367375 0.7516218 0.5699914
#>       [,58]     [,59]     [,60]
#> 4 0.5259546 0.7097911 0.7556622

# do.call(fun, c(args, list(otherargs)))
# following doesn't work!
res = do.call(c, c(mats, list(decorators = c("CoreStatistics", "ExoticStatistics"))))
#> Error in d$getParameterValue: $ operator is invalid for atomic vectors
```

<sup>Created on 2023-10-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by RaphaelS1** [comment]
@bblodfon this should fix it - please double check and let me know (it worked for me against the example above) https://github.com/xoopR/distr6/pull/295

**Comment by RaphaelS1** [comment]
I still think the difference makes sense though because VectorDistributions are built to combine any abstract combination, so pushing decorators manually fits with that
