### ISSUE TITLE
refactor parameter names in vectorized C++ functions

### ISSUE THREAD

**Issue by bblodfon** [xoopR/distr6#297]
The following functions have parameters `x` and `data`:
- `C_Vec_WeightedDiscretePdf`
- `C_Vec_WeightedDiscreteCdf`

1) Refactor name `x` to `xnew` and `data` to `x` - also in other places where these functions are used
2) Write some internal code doc about what these functions actually do => e.g. gets a `pdf` matrix and subsets it to the `x` times (points) instead of the `data` that has been retrieved via i.e. `gprm(distr, "x")`.

The above is just an example, probably we will need to clear up other similar C++-calling functions

**Comment by RaphaelS1** [comment]
@bblodfon I agree we *should* do this but I'm not going to.  It's a messy refactor that is incredibly error-prone because we're swapping names between parameters (i.e. first stops being `x` and second starts being). These are really internal functions and shouldn't be used externally
