### ISSUE TITLE
assertion functions for skew failing 

### ISSUE THREAD

**Issue by Rosie23** [xoopR/distr6#299]
Functions `testNoSkew()`, `checkNoSkew()`, `assertNoSkew()`, `testNegativeSkew()`, `checkNegativeSkew()`, `testPositiveSkew()`, `checkPositiveSkew()`, `assertPositiveSkew()` do not work correctly.

Function uses `skewType(object$skewness()) == "No Skew"`  (uppercase) however `skewType()` returns skew in all lowercase returning a FALSE irrespective of skew.

Failing tests
`expect_true(testNoSkew( Binomial$new()))`

**Comment by RaphaelS1** [comment]
Thanks @Rosie23 - fixed here https://github.com/xoopR/distr6/pull/300
