### ISSUE TITLE
Dead link behind 'not on CRAN'

### ISSUE THREAD

**Issue by MichaelChirico** [xoopR/distr6#301]
https://github.com/xoopR/distr6/blob/a7c01f7166f67ebbfdc8bec4b5625ab911af85c4/README.md?plain=1#L177-L179

That link is dead -- could you please update it or remove it?

**Comment by RaphaelS1** [comment]
https://github.com/xoopR/distr6/commit/95d7359fb85698529981bf66da7674d3b8c00e6c
